version: '3'
services:
  nextjs:
    image: docker-nextjs-dev
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/usr/app/pages
      - ./public:/usr/app/public
      - ./styles:/usr/app/styles
      - ./useCases:/usr/app/useCases
      - ./useComponents:/usr/app/useComponents
      - ./usePieces:/usr/app/usePieces
      - ./store:/usr/app/store